# Generated by Django 4.0.4 on 2022-05-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='idid',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='what',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='updated_at',
            new_name='when',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='created_at',
            new_name='who',
        ),
        migrations.RemoveField(
            model_name='news',
            name='photo',
        ),
        migrations.AddField(
            model_name='news',
            name='where',
            field=models.TextField(blank=True),
        ),
    ]
